name: deploy multi region setup
description: deploys the multi region setup

inputs:
  env:
    description: "Environment"
    required: true
  aws_account_id:
    description: "Account ID for the AWS account"
    required: true
  aws_region:
    description: "AWS region"
    required: true
  teams_url:
    description: "URL for Teams"
    required: true
  tf_workspace:
    description: name of terraform workspace
    required: true
  provider_region:
    description: "Provider region"
    required: true
  primary_region_url:
    description: "URL for the primary region"
    required: true
  secondary_region_url:
    description: "URL for the secondary region"
    required: true
  hosted_zone_id:
    description: "Hosted Zone ID"
    required: true
  domain_name:
    description: "Domain name"
    required: true
  environment:
    description: "Environment"
    required: true
  cognito_username:
    description: "Username for Cognito service account"
    required: true
  cognito_password:
    description: "Password for Cognito service account"
    required: true
  region_1_health_check_id:
    description: "Health check ID for region 1"
    required: true
  region_2_health_check_id:
    description: "Health check ID for region 2"
    required: true
  primary_region:
    description: "Primary AWS region"
    required: true
  secondary_region:
    description: "Secondary AWS region"
    required: true
  primary_websocket_url:
    description: "WebSocket URL for the primary region"
    required: true
  secondary_websocket_url:
    description: "WebSocket URL for the secondary region"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Download Lambda Packages
      uses: actions/download-artifact@v3
      with:
        name: lambda-package
        path: terraform
    - name: Use Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false
    - name: Terraform Format
      id: fmt
      shell: bash
      run: terraform fmt -check
      working-directory: terraform/multi-region
    - name: Set Up Terraform Workspace for Multi Region
      uses: sorenson-eng/shared-github-actions/create-tf-cloud-workspace@main
      with:
        apiToken: ${{ secrets.TF_API_TOKEN }}
        teamID: team-9oiEbg9n7LRqH8ch
        terraformWorkspaceName: ${{ inputs.tf_workspace }}
        tfVarSet: varset-f2C3DJRZHGfvpwdR
        terraformDir: terraform/multi-region
    - name: Terraform Init for Multi region
      shell: bash
      id: init_mr
      run: terraform init
      working-directory: terraform/multi-region
    - name: Terraform Plan for Multi region
      shell: bash
      id: plan_mr
      run: terraform plan
      working-directory: terraform/multi-region
      env:
        TF_VAR_aws_account_id: '${{ inputs.aws_account_id}}'
        TF_VAR_provider_region: '${{ inputs.aws_region}}'
        TF_VAR_primary_region_url: '${{ inputs.primary_region_url }}'
        TF_VAR_secondary_region_url: '${{ inputs.secondary_region_url }}'
        TF_VAR_hosted_zone_id: '${{ inputs.hosted_zone_id }}'
        TF_VAR_domain_name: '${{ inputs.domain_name}}'
        TF_VAR_environment: '${{ inputs.environment }}'
        TF_VAR_cognito_username: ${{ inputs.cognito_username}
        TF_VAR_cognito_password: ${{ inputs.cognito_password}}
        TF_VAR_teams_url: ${{ inputs.teams_url}}
        TF_VAR_region_1_health_check_id: ${{ inputs.region_1_health_check_id }}
        TF_VAR_region_2_health_check_id: ${{ inputs.region_2_health_check_id }}
        TF_VAR_primary_region: ${{ inputs.primary_region }}
        TF_VAR_secondary_region: ${{ inputs.secondary_region }}
        TF_VAR_primary_websocket_url: ${{ inputs.primary_websocket_url }}
        TF_VAR_secondary_websocket_url: ${{ inputs.secondary_websocket_url }}
        TF_VAR_websocket_domain_name: ${{ inputs.websocket_domain_name }}
    - name: Terraform Apply for Multi region
      shell: bash
      id: apply_mr
      run: terraform apply --auto-approve
      working-directory: terraform/multi-region
      env:
        TF_VAR_aws_account_id: '${{ inputs.aws_account_id}}'
        TF_VAR_provider_region: '${{ inputs.aws_region}}'
        TF_VAR_primary_region_url: '${{ inputs.primary_region_url }}'
        TF_VAR_secondary_region_url: '${{ inputs.secondary_region_url }}'
        TF_VAR_hosted_zone_id: '${{ inputs.hosted_zone_id }}'
        TF_VAR_domain_name: '${{ inputs.domain_name}}'
        TF_VAR_environment: '${{ inputs.environment }}'
        TF_VAR_cognito_username: ${{ inputs.cognito_username}
        TF_VAR_cognito_password: ${{ inputs.cognito_password}}
        TF_VAR_teams_url: ${{ inputs.teams_url}}
        TF_VAR_region_1_health_check_id: ${{ inputs.region_1_health_check_id }}
        TF_VAR_region_2_health_check_id: ${{ inputs.region_2_health_check_id }}
        TF_VAR_primary_region: ${{ inputs.primary_region }}
        TF_VAR_secondary_region: ${{ inputs.secondary_region }}
        TF_VAR_primary_websocket_url: ${{ inputs.primary_websocket_url }}
        TF_VAR_secondary_websocket_url: ${{ inputs.secondary_websocket_url }}
        TF_VAR_websocket_domain_name: ${{ inputs.websocket_domain_name }}
    - name: Send Chat Fail Notification
      if: failure()
      uses: sorenson-eng/shared-github-actions/send-teams-notification@main
      with:
        TeamsWebhookUrl: ${{ secrets.MSTEAMS_WEBHOOK }}
        jobName: '${{ github.job }}'
        jobUrl: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        jobRepo: ${{ github.repository }}
        triggeredBy: '${{ github.actor }}'