name: PyFilePipeline

on:
  push:
    branches:
      - main

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/checkout@v2
    
    - uses: actions/upload-artifact@v2
      with:
        name: python-script
        path: scripts/test.py

  download_artifact:
    runs-on: ubuntu-latest
    needs: upload_artifact

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: python-script
        path: scripts

