name: On Delete Workflow

on:
  delete:

jobs:
  on-delete-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Display information on delete
      run: |
        echo "This workflow was triggered by a delete event."
        echo "Deleted branch/tag: ${{ github.ref }}"