on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
env:
  e1: smth

jobs:
  ijob1:
    runs-on: ubuntu-latest
    environment: ${{inputs.env}}
    outputs:
      region1: ${{ steps.tf_output.outputs.dev_region }}
      region2: ${{ steps.tf_output.outputs.prod_region }}
    strategy:
      matrix:
        include:
          - env: dev
          - env: prod
    steps:
      - uses: actions/checkout@v3
      - name: custom action
        id: tf_output
        uses: ./.github/actions/test
        with:
          env: ${{ matrix.env }}

  ijob2:
    needs: ijob1
    runs-on: ubuntu-latest
    steps:
      # - run: echo ${{needs.job1.outputs.region1}}
      # - run: echo ${{needs.job1.outputs.region2}}
      - run: echo ${{secrets.DT_URL}}
      - run: echo ${{ github.job }}
      - run: echo ${{ 'a' == 'b' && 'hi' || 'hello' }}
      - run: echo ${{ env.e1 }}
