name: test

on:
  push:
    branches:
      - main
env:
  e1: smth
  e2: ${{ startsWith('prod-eur', 'prod') && 'a' || 'b'}}

jobs:
  # j1:
  #   environment: test1
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo ${{secrets.smh}}
  
  # j2:
  #   runs-on: ubuntu-latest
  #   needs: j1
  #   steps:
  #     - run: echo ${{secrets.smh}}

  # check:
  #   name: Check files in a specific folder
  #   outputs:
  #     run_job: ${{ steps.check_files.outputs.run_job }}
  #   runs-on: ubuntu-latest
  #   env:
  #     DIRECTORY_TO_CHECK: base_infra
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 2

  #     - name: check modified files
  #       id: check_files
  #       run: |
  #         echo "=============== list modified files ==============="
  #         # Check for changes in the specified directory
  #         git diff --name-only HEAD^ HEAD "$DIRECTORY_TO_CHECK/"

  #         echo "========== check if there are modified files =========="
  #         if [[ -n $(git diff --name-only HEAD^ HEAD "$DIRECTORY_TO_CHECK/") ]]; then
  #           echo "There are modified files in the '$DIRECTORY_TO_CHECK' folder."
  #           echo "run_job=true" >> "$GITHUB_OUTPUT"
  #         else
  #           echo "There are no modified files in the '$DIRECTORY_TO_CHECK' folder."
  #           echo "run_job=false" >> "$GITHUB_OUTPUT"
  #         fi

  # rjob1:
  #   uses: ${{vars.ENABLE_BG == 'true' && './.github/workflows/helper_prod.yml'}}
  #   secrets: inherit
    

  # rjob2:
  #   # strategy:
  #   #   matrix:
  #   #     target: [test1, test1]
  #   uses: ./.github/workflows/helper_prod.yml
  #   needs: rjob1
  #   secrets: inherit
  #   with:
  #     # env: ${{matrix.target}}
  #     env: test1

  # rjob2:
  #   # strategy:
  #   #   matrix:
  #   #     target: [prod]
  #   uses: ./.github/workflows/helper_prod.yml
  #   secrets: inherit
  #   with:
  #     env: test1

  # job1:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     region1: ${{ steps.tf_output.outputs.dev_region }}
  #     region2: ${{ steps.tf_output.outputs.prod_region }}
  #   strategy:
  #     matrix:
  #       include:
  #         - env: dev
  #         - env: prod
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: custom action
  #       id: tf_output
  #       uses: ./.github/actions/test
  #       with:
  #         env: ${{ matrix.env }}

  # job2:
  #   needs: job1
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo ${{needs.job1.outputs.region1}}
  #     - run: echo ${{needs.job1.outputs.region2}}

  # base_infra:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v3

  #     - name: custom action
  #       uses: ./.github/actions/test
  #       with:
  #         smth: 'true'


  # other_jobs:
  #   needs: base_infra
  #   if: ${{ always() && github.ref == 'refs/heads/main'}}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print Message
  #       run: echo hello

  # job1:
  #   runs-on: ubuntu-latest
  #   environment: test1
  #   strategy:
  #     matrix:
  #       include:
  #         - env: "dev"
  #         - env: "prod"
  #   steps:
  #     - run: echo ${{matrix.env}}

  # job2:
  #   runs-on: ubuntu-latest
  #   environment: test1
  #   needs: job1
  #   strategy:
  #     matrix:
  #       include:
  #         - env: "dev"
  #         - env: "prod"
  #   steps:
  #     - run: echo ${{matrix.env}}

  # job1:
  #   uses: ./.github/workflows/helper_prod.yml
  #   secrets: inherit
  #   with:
  #     env: false

  # job2:
  #   # needs: job1
  #   uses: ./.github/workflows/helper_prod.yml
  #   secrets: inherit
  #   with:
  #     env: test2

  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{secrets.ABC}} > abc.txt
      - uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: ./abc.txt
      - name: Download artifact
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: env-file
          path: .
      
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: smth
  #         path: scripts

  # job2:
  #   environment: test1
  #   needs: job1
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo j2