name: dynatrace

on:
  push:
    branches:
      - main

jobs:
  dyna:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: build the version
        shell: bash
        run: |
          chmod +x ./scripts/ver.sh
          $output=(./scripts/ver.sh | awk -F 'ver: *' '{print $2}' | xargs)
          echo "::set-output name=app_version::$output"

      - name: Build count
        uses: dynatrace-oss/dynatrace-github-action@v9
        with:
          url: ${{ secrets.DT_URL }}
          token: ${{ secrets.DT_TOKEN }}
          metrics: |
            - metric: "github.metric1"
              value: "${{ steps.run-script.outputs.app_version }}"
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: vignesh
