name: test

on:
  push:
    branches:
      - main

jobs:
  printa:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message1
        run: echo hi
      - name: Print Message2
        run: echo $helo

  printb:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo hello