name: test

on:
  push:
    branches:
      - main

jobs:
  print-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hi
        run: echo "Hi"

  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello"
