name: manual trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'
        required: true
        type: choice
        options:
        - prod-na
        - prod-eur
        - prod-apse

env:
  ACCOUNT_CONFIGS: '{"prod-na": "${{vars.TEMP}}1", "prod-eur": "${{vars.TEMP}}2", "prod-apse": "${{secrets.SE1}}"}'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ fromJSON(env.ACCOUNT_CONFIGS)[inputs.environment] }}
      